name: pro_stress
dependencies:
  flutter:
    sdk: flutter
  battery_plus: ^6.1.0
  wakelock_plus: ^1.2.8
  screen_brightness: ^1.0.1
  path_provider: ^2.1.3
  cupertino_icons: ^1.0.8
flutter:
  uses-material-design: true
